### ISSUE TITLE
_color.css の !important を削除したい

### ISSUE THREAD

**Issue by DesignChips** [DesignChips/Sushi#4]
## 現象
form:invalidにスタイルを適用すると、form:validで解除しないといけなくなる。
.parimaryなど色のクラスに!importantがついていないと、form:validで.primaryの色を適用する手段がなくなるので、.parimaryに!importantを付与している。

## 困ること
- 色に毎回!importantをつけないといけなくて面倒。
- 色の詳細度が上がるので、将来的に不具合につながる可能性がある。

```css
form:invalid button.submit {
	color: var(--disabled-text) !important;
	background-color: var(--disabled-bg) !important;
	border-color: var(--disabled-text) !important;
}
```
